# Generated by Django 2.2.3 on 2019-08-09 18:23

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190807_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
